name: automation deploy

on:
  push:
    branches: [main]

jobs:
  deploy_main:
    name: Deploy to main server
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: chekcout repo
        uses: actions/checkout@v2
      - name: Set Git safe directory
        run: git config --global --add safe.directory /var/www/ips
      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/ips
            sudo git pull origin main
            sudo composer update --optimize-autoloader --no-dev
            sudo composer install --no-interaction --prefer-dist --optimize-autoloader
            sudo composer dump-autoload
            sudo php artisan key:generate
            sudo php artisan cache:clear
            sudo php artisan view:clear
            sudo php artisan config:clear
            sudo php artisan optimize
            sudo composer require fruitcake/laravel-cors
            sudo php artisan vendor:publish --provider="Fruitcake\Cors\ServiceProvider"
